[package]
name = "merkle-trie-cli"
version = "0.2.0"
edition = "2021"

[dependencies]
tiny-keccak = { version = "2.0", features = ["keccak"] }
hex = "0.4.3"

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1
opt-level = "z"

[workspace]
