[[contracts]]
address = "0x0123456789abcdef0123456789abcdef01234567"
abi_path = "./abis/SimpleEvent.json"

[[contracts]]
address = "0x89abcdef0123456789abcdef0123456789abcdef"
abi_path = "./abis/OtherEvent.json"
