# Application configuration for Blockscout contract fetcher
blockscout:
  # Blockscout server URL (without trailing slash)
  server: "https://blockscout.server"

  # Optional: HTTP Basic Auth credentials
  # If not set here, can be provided via environment variables:
  # export BLOCKSCOUT_AUTH_USER="username"
  # export BLOCKSCOUT_AUTH_PASSWORD="password"
  auth_user: null # "username"
  auth_password: null # "password"

  # API path (with leading slash)
  api_path: "/api/v2"

  # Request timeout in seconds (optional, defaults to 30)
  request_timeout_seconds: 10

  # Maximum retries for failed requests (optional, defaults to 3)
  max_retries: 10

  max_implementations_per_contract: null # 1  # Set to null or omit for unlimited
  max_implementation_nesting_depth: null # 0  # Set to null or omit for unlimited (defaults to 10)

output:
  # Output file path for contracts YAML
  contracts_file: "contracts_output.yaml"

  # Directory to save ABI JSON files
  abi_directory: "./abi"

  # Directory to save event signature files
  events_directory: "./events"

  # Output file path for events YAML
  events_file: "events_output.yaml"

  # Output file path for contracts events YAML with extended signatures
  contracts_events_file: "contracts_events.yaml"
