version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: indexer
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  nats:
    image: nats:2.10-alpine
    command: ["-js"]
    ports: ["4222:4222", "8222:8222"]

  indexer:
    build: .
    depends_on:
      - db
      - nats
    environment:
      RUST_LOG: info
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./schema.sql:/app/schema.sql:ro
      - ./abi:/app/abi:ro

volumes:
  pgdata: {}
