version: '3.9'

services:

  indexer:
    build: .
    depends_on:
      - db
      - nats
    environment:
      RUST_LOG: debug
    volumes:
      - ./abi/:/apps/abi/
      - ./config.toml:/apps/config.toml
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: indexer
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  nats:
    image: nats:2-scratch
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  pgdata:
